load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# rules_oci for building container images
http_archive(
    name = "rules_oci",
    sha256 = "56d5499025d67a6b86b2e6ebae5232c72104ae682b5a21287770bd3bf0661abf",
    strip_prefix = "rules_oci-1.7.5",
    url = "https://github.com/bazel-contrib/rules_oci/releases/download/v1.7.5/rules_oci-v1.7.5.tar.gz",
)

load("@rules_oci//oci:dependencies.bzl", "rules_oci_dependencies")
rules_oci_dependencies()

load("@rules_oci//oci:repositories.bzl", "LATEST_CRANE_VERSION", "oci_register_toolchains")
oci_register_toolchains(
    name = "oci",
    crane_version = LATEST_CRANE_VERSION,
)

# Pull base Python image with CUDA support
load("@rules_oci//oci:pull.bzl", "oci_pull")

# Using Python 3.10 slim as base (we'll install PyTorch with CUDA separately)
oci_pull(
    name = "python_base",
    image = "index.docker.io/library/python",
    platforms = ["linux/amd64"],
    tag = "3.10-slim",
)

# Alternative: NVIDIA CUDA base image (if needed for GPU support)
oci_pull(
    name = "cuda_base",
    image = "index.docker.io/nvidia/cuda",
    platforms = ["linux/amd64"],
    tag = "12.1.0-runtime-ubuntu22.04",
)
